### ISSUE TITLE
Sorting happens only for first time

### ISSUE THREAD

**Issue by couragecowardlydog** [priyanka020593/EmployeeList#1]
Clicking on sort control sorts the only for the first time. Then on, only the image is randomized, list isn't getting sorted

**Comment by priyankasenni** [comment]
> Clicking on sort control sorts the only for the first time. Then on, only the image is randomized, list isn't getting sorted

1. Request to clarify if sorting is required when sort control is pressed after first time.
2. The control for sort was done for only sorting the list by age for first time. Clicking sort multiple times will not result in change of the sorted list (as its already sorted) and the profile image changes because of the randomizer function.

**Comment by couragecowardlydog** [comment]
Yes .. it's similar to sorting you see in any other website, every time pressing on sort control changes the current sorting order

**Comment by couragecowardlydog** [comment]
I have used apk from the latest commit, even though sorting happens for the first time,

Take look here..,

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sort_list_desc
